platform :ios, '10.0'
use_frameworks!

target 'PAVietNam' do
    # Alamofire (Networking)
    pod 'Alamofire'
    
    # Reachability
    pod 'Reachability'
    
    # CYLTabBarController
    pod 'CYLTabBarController', '1.8.0'
    
    # TTTAttributedLabel
    pod 'TTTAttributedLabel'
    
    # HockeySDK
    # pod 'HockeySDK', '~> 4.1.4'
    
    # ObjectMapper - auto mapper data
    pod 'ObjectMapper'
    pod 'SwiftyJSON'
    
    # AlamofireImage - Image Fetcher
    pod 'AlamofireImage'
    
end

